### ISSUE TITLE
download fdk-aac code before compiling

### ISSUE THREAD

**Issue by divyamML** [kewlbear/fdk-aac-build-script-for-iOS#2]
I had to do a wget from https://github.com/mstorsjo/fdk-aac

**Comment by kewlbear** [comment]
Downloading source code is out of scope of this script.

**Comment by divyamML** [comment]
I see fatal error "'ac_nonexistent.h' file not found" in config.log
and then I see below on std out - 

copying selected object files to avoid basename conflicts...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(aacenc_hcr.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(sbr_deb.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(scale.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(aacenc_hcr.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(sbr_deb.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(scale.o) has no symbols

**Comment by divyamML** [comment]
although it does create libfdk-aac.a, but on compiling ffmpeg it's not able to find symbols in libfdk-aac and fails
