### ISSUE TITLE
complilation errors/warnings

### ISSUE THREAD

**Issue by divyamML** [kewlbear/fdk-aac-build-script-for-iOS#3]
I see fatal error "'ac_nonexistent.h' file not found" in config.log
and then I see below on std out -
copying selected object files to avoid basename conflicts...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(aacenc_hcr.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(sbr_deb.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(scale.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(aacenc_hcr.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(sbr_deb.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libfdk-aac.a(scale.o) has no symbols

although it does create libfdk-aac.a, but on compiling ffmpeg it's not able to find symbols in libfdk-aac and fails

**Comment by kewlbear** [comment]
Did you remove arm64 when building FFmpeg?
